### ISSUE TITLE
use_git_ignore()

### ISSUE THREAD

**Issue by krlmlr** [r-pkgs/usethis#3]
and perhaps `use_ignore()` which adds to both `.Rbuildignore` and `.gitignore`.

**Comment by hadley** [comment]
There is a `use_git_ignore` already. I think a `use_ignore` would be more challenging because you have to think about the different escaping rules.  There don't seem to be too many files that need both sorts of ignoring (it's usually one or the other) so I'm going to close for now.

**Comment by krlmlr** [comment]
I think you'd never *not* .Rbuildignore a file that is .gitignore-d. IDE and other autogenerated files are a common example where we ignore both.
